// Envelope: the one shape every conversation fact on this mesh has -- a
// room message, a central broadcast, a lifecycle marker. The wire
// contract and the reasoning are in plans/PLAN_AGENT_CONVERSATIONS.md
// section 3; this module is that contract in code, pure and
// subprocess-free so every rule can be unit-tested.
//
// Wire rules that shaped it (mesh://etiquette): no booleans anywhere
// (sent_at is an integer, nothing here is a flag); ids travel in the
// payload, never in the topic name (a room topic's hex is a shared
// secret, not an identifier; message_id/in_reply_to/room_topic all ride
// inside the fact); kinds are business verbs, never CRUD.

import { randomBytes } from "node:crypto";

/** Central: the one topic every present agent keeps watching, for broadcasts to whoever is around. */
export const CENTRAL_TOPIC = "agents.lobby";
/** A room topic is this prefix plus 32 hex chars generated by the opener -- unguessable, not encrypted. */
export const ROOM_TOPIC_PREFIX = "agents.room.";

export const LIFECYCLE_KINDS = ["room_opened", "participant_joined", "participant_left", "room_closed"] as const;
export const TALK_KINDS = [
  "question_asked",
  "answer_given",
  "help_offered",
  "help_requested",
  "task_handed_over",
  "result_reported",
  "remark_made",
] as const;
export const KINDS = [...LIFECYCLE_KINDS, ...TALK_KINDS] as const;
export type Kind = (typeof KINDS)[number];

/** Kinds that only make sense as a reply: an answer without a question, or a result without a task, is a bug, not a message. */
export const REPLY_REQUIRED_KINDS: ReadonlySet<string> = new Set(["answer_given", "result_reported"]);

export interface Envelope {
  /** 32 hex, random, generated by the sender. */
  message_id: string;
  /** The topic this was published on -- present so a message quoted elsewhere stays attributable. */
  room_topic: string;
  /** message_id of what this replies to; required for answer_given and result_reported. */
  in_reply_to?: string;
  /** Sender clock, unix ms, informational. Never negative (stations drop negative integers). */
  sent_at: number;
  /** Presence node id of the sender (64 hex) -- the one mesh_agents shows. */
  from: string;
  /** Citizen id once the citizen plan lands; absent until then. */
  from_citizen?: string;
  kind: Kind;
  /** May be empty for lifecycle kinds. */
  text: string;
  /** mesh_artifact ids for anything large -- never inline content. */
  refs?: string[];
  /** room_opened only: node ids the opener means to be in the room, itself included. */
  participants?: string[];
  /** room_opened only: why the room exists, one line. */
  purpose?: string;
}

const HEX32 = /^[0-9a-f]{32}$/;
const HEX64 = /^[0-9a-fA-F]{64}$/;

export function isKind(s: unknown): s is Kind {
  return typeof s === "string" && (KINDS as readonly string[]).includes(s);
}

export function newMessageId(): string {
  return randomBytes(16).toString("hex");
}

export function newRoomTopic(): string {
  return `${ROOM_TOPIC_PREFIX}${randomBytes(16).toString("hex")}`;
}

export function isRoomTopic(topic: string): boolean {
  return topic.startsWith(ROOM_TOPIC_PREFIX) && HEX32.test(topic.slice(ROOM_TOPIC_PREFIX.length));
}

/** A topic an envelope may travel on: central, or a room. */
export function isConversationTopic(topic: string): boolean {
  return topic === CENTRAL_TOPIC || isRoomTopic(topic);
}

export class EnvelopeError extends Error {}

export interface BuildInput {
  room_topic: string;
  from: string;
  kind: Kind;
  text?: string;
  in_reply_to?: string;
  refs?: string[];
  participants?: string[];
  purpose?: string;
  from_citizen?: string;
}

/** Builds a fresh, valid envelope (new message_id, sent_at = now) or throws EnvelopeError naming every problem. Optional keys are omitted, not sent as null. */
export function buildEnvelope(input: BuildInput): Envelope {
  const env: Envelope = {
    message_id: newMessageId(),
    room_topic: input.room_topic,
    sent_at: Date.now(),
    from: input.from,
    kind: input.kind,
    text: input.text ?? "",
    ...(input.in_reply_to !== undefined ? { in_reply_to: input.in_reply_to } : {}),
    ...(input.from_citizen !== undefined ? { from_citizen: input.from_citizen } : {}),
    ...(input.refs !== undefined ? { refs: input.refs } : {}),
    ...(input.participants !== undefined ? { participants: input.participants } : {}),
    ...(input.purpose !== undefined ? { purpose: input.purpose } : {}),
  };
  const problems = envelopeProblems(env);
  if (problems.length > 0) throw new EnvelopeError(problems.join("; "));
  return env;
}

/**
 * Every way a payload fails to be an envelope, as human-readable
 * strings; empty means valid. Exported (rather than a boolean) so a
 * reader can say WHY a fact was left unparsed, and so tests can pin
 * each rule individually.
 */
export function envelopeProblems(payload: unknown): string[] {
  if (typeof payload !== "object" || payload === null || Array.isArray(payload)) return ["not an object"];
  const p = payload as Record<string, unknown>;
  const problems: string[] = [];

  for (const [key, value] of Object.entries(p)) {
    if (typeof value === "boolean") problems.push(`boolean at "${key}" -- the wire has no bool type, use 0/1`);
  }

  if (typeof p.message_id !== "string" || !HEX32.test(p.message_id)) problems.push("message_id must be 32 lowercase hex chars");
  if (typeof p.room_topic !== "string" || !isConversationTopic(p.room_topic)) {
    problems.push(`room_topic must be "${CENTRAL_TOPIC}" or "${ROOM_TOPIC_PREFIX}<32 hex>"`);
  }
  if (!Number.isInteger(p.sent_at) || (p.sent_at as number) < 0) problems.push("sent_at must be a non-negative integer (unix ms)");
  if (typeof p.from !== "string" || !HEX64.test(p.from)) problems.push("from must be a 64-hex node id");
  if (!isKind(p.kind)) problems.push(`kind must be one of ${KINDS.join(", ")}`);
  if (typeof p.text !== "string") problems.push("text must be a string (may be empty)");

  if (p.in_reply_to !== undefined && (typeof p.in_reply_to !== "string" || !HEX32.test(p.in_reply_to))) {
    problems.push("in_reply_to, when present, must be a 32-hex message_id");
  }
  if (isKind(p.kind) && REPLY_REQUIRED_KINDS.has(p.kind) && p.in_reply_to === undefined) {
    problems.push(`${p.kind} must carry in_reply_to`);
  }
  if (p.from_citizen !== undefined && (typeof p.from_citizen !== "string" || p.from_citizen.length === 0)) {
    problems.push("from_citizen, when present, must be a non-empty string");
  }
  if (p.refs !== undefined && !(Array.isArray(p.refs) && p.refs.every((r) => typeof r === "string" && r.length > 0))) {
    problems.push("refs, when present, must be a list of non-empty strings");
  }
  if (p.participants !== undefined && !(Array.isArray(p.participants) && p.participants.every((n) => typeof n === "string" && HEX64.test(n)))) {
    problems.push("participants, when present, must be a list of 64-hex node ids");
  }
  if (p.purpose !== undefined && typeof p.purpose !== "string") problems.push("purpose, when present, must be a string");

  return problems;
}

/** The envelope, with only its known keys, or undefined if the payload isn't one. */
export function parseEnvelope(payload: unknown): Envelope | undefined {
  if (envelopeProblems(payload).length > 0) return undefined;
  const p = payload as Record<string, unknown>;
  const env: Envelope = {
    message_id: p.message_id as string,
    room_topic: p.room_topic as string,
    sent_at: p.sent_at as number,
    from: p.from as string,
    kind: p.kind as Kind,
    text: p.text as string,
  };
  if (p.in_reply_to !== undefined) env.in_reply_to = p.in_reply_to as string;
  if (p.from_citizen !== undefined) env.from_citizen = p.from_citizen as string;
  if (p.refs !== undefined) env.refs = p.refs as string[];
  if (p.participants !== undefined) env.participants = p.participants as string[];
  if (p.purpose !== undefined) env.purpose = p.purpose as string;
  return env;
}

export interface ObservedEnvelope extends Envelope {
  /** When THIS process saw it -- the transcript's clock, not the sender's. */
  observed_at: string;
  /** message_id of the first message in this thread (itself, for a root). */
  thread_root: string;
  /** 0 for a root, parent's depth + 1 for a reply. */
  depth: number;
  /**
   * 1 when the station-attested publisher of the fact is the node id the
   * envelope claims in `from`; 0 when they differ or the publisher is
   * unknown (a row from before publishers were recorded). `from` alone
   * is a self-claim anyone can write; only attested messages count for
   * anything that matters (who joined, who replied, who opened).
   */
  attested: 0 | 1;
}

/** Whether `from` is backed by the station's own record of who published the fact. */
export function isAttested(from: string, publisher: string | null | undefined): boolean {
  return typeof publisher === "string" && publisher.toLowerCase() === from.toLowerCase();
}

/**
 * Turns observed facts (in arrival order) into threaded envelopes. Two
 * passes, so a reply that arrived BEFORE its parent (out-of-order
 * delivery) still threads under the parent's root. A reply whose parent
 * isn't in the window at all threads under that parent's id at depth 1
 * -- the window is a page of a transcript, not the whole history. Facts
 * that aren't envelopes are counted, not dropped silently.
 */
export function threadEnvelopes(rows: { payload: unknown; observed_at: string; publisher?: string | null }[]): { messages: ObservedEnvelope[]; unparsed: number } {
  const parsed: { env: Envelope; observed_at: string; publisher?: string | null }[] = [];
  let unparsed = 0;
  for (const row of rows) {
    const env = parseEnvelope(row.payload);
    if (!env) {
      unparsed += 1;
      continue;
    }
    parsed.push({ env, observed_at: row.observed_at, publisher: row.publisher });
  }
  const byId = new Map<string, Envelope>();
  for (const p of parsed) byId.set(p.env.message_id, p.env);
  const resolve = (env: Envelope): { root: string; depth: number } => {
    let root = env.message_id;
    let depth = 0;
    let cur: Envelope | undefined = env;
    const seen = new Set<string>([env.message_id]);
    while (cur?.in_reply_to !== undefined) {
      depth += 1;
      const parent = byId.get(cur.in_reply_to);
      if (!parent || seen.has(parent.message_id)) {
        root = cur.in_reply_to;
        break;
      }
      seen.add(parent.message_id);
      root = parent.message_id;
      cur = parent;
    }
    return { root, depth };
  };
  const messages: ObservedEnvelope[] = parsed.map((p) => {
    const { root, depth } = resolve(p.env);
    return { ...p.env, observed_at: p.observed_at, thread_root: root, depth, attested: isAttested(p.env.from, p.publisher) ? 1 : 0 };
  });
  return { messages, unparsed };
}
